name: CosmicFactions
version: 1.0.0
author: Terpz710
api: 5.0.0
main: Terpz710\CosmicFactions\Factions
description: A simple factions plugin for PocketMine-MP

permissions:
  factions.cmd:
    default: true